installer:
  spec:
    kubernetes:
      version: 1.22.5
    containerd:
      version: latest
    weave:
      version: latest
    prometheus:
      version: 0.46.0
output:
  - message: Prometheus versions <= 0.49.0-17.1.3 are not compatible with Kubernetes 1.22+
    field: spec.prometheus.version
    type: incompatibility
